### ISSUE TITLE
PyPI name transfer

### ISSUE THREAD

**Issue by jamadden** [vivisect/dissect#7]
Hello, 

I'm a moderator for pypi.org. In https://github.com/pypa/warehouse/issues/5939 it's been requested to transfer the project name `dissect` to a different user for use on an unrelated project. [PEP 541](https://www.python.org/dev/peps/pep-0541/) allows that without the original owner's consent if the original owner is unreachable (among other criteria).

Could you please respond to that issue and let the requester know your thoughts?

**Comment by invisig0th** [comment]
Can do. Sorry about the delays.  thanks :)

**Comment by jamadden** [comment]
Hi @invisig0th , any updates on when this can happen?

**Comment by yeraydiazdiaz** [comment]
Hello again @invisig0th, could you please clarify you position regarding this request? Your previous reply doesn't say if you'd like to keep ownership or are happy to transfer it to @Schamper.

Either here or on the [pypi-support issue](https://github.com/pypa/pypi-support/issues/16).
